### ISSUE TITLE
Mobile Website Horizontal Scrolling

### ISSUE THREAD

**Issue by JulianWebb** [KyleCulp/spotifyoverlay#4]
Device: SM-J327W
Android: 7.0
Browser: Firefox
Version: 62.0.2

Issue: Images on homepage cause horizontal scrolling as they bleed past the boundaries.
![image](https://user-images.githubusercontent.com/471907/45936955-03c12780-bf71-11e8-8798-681d678a7884.png)

Steps to reproduce:
1. Visit site with Firefox on Android

**Comment by KyleCulp** [comment]
Yeah it's not just firefox. It works with chrome's mobile emulation, but doesn't actually work. Tested on chrome and safari mobile as well. I intend on a redesign of the front page anyways, so it will be fixed soon.
